### PR TITLE
Update integration installation docs

### PR DESCRIPTION
**Pull request by mhoss019**
This PR fixes #

## Checklist
* [x] I have signed the CLA
* [x] I have updated/added any relevant documentation

### What's the goal of this PR?
Update integration installation docs

### CODE REVIEW

**Comment by mhoss019** [comment]
Why is it not liking the links? They work locally. It's something to do with the #?

**Comment by rbren** [comment]
It's very picky. I think you need to remove the trailing `/`

**Comment by mhoss019** [comment]
> It's very picky. I think you need to remove the trailing `/`

Yeah but then it doesn't actually work

**Comment by mhoss019** [comment]
That's actually really weird. It doesn't work locally but it works when it actually deploys? lol

**Comment by rbren** [comment]
Huh that's odd. I wonder if it's a version issue? I think the links generally work for me

**Comment by mhoss019** [comment]
It's okay. I won't lost sleep over this :D
Thanks for the fix!

**Pull request merged**
